name: python_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.2.1
  - numpy=1.18.4
  - pandas=1.0.3
  - pathlib
  - python=3.6.10
  - scipy=1.4.1
  - time
  - tqdm=4.46.0
  - pip:
    - anndata==0.7.3
    - scanpy==1.5.1
    - scvelo==0.2.1
    - seaborn==0.10.1
    - umap-learn==0.4.4
